### ISSUE TITLE
수연님 저희 마이그레이션 파일에 대한 회의가 필요합니다.

### ISSUE THREAD

**Issue by soheon-lee** [hong-dev/GreatBobFulRain-backend#11]
은우님으로부터 migration파일 무조건 테이블 하나당 하나 만들 필요 절대 없고, 괜히 마이그레이션 파일 많아지면 테이블 구조 파악하기에 더 어려워질 수 있다는 피드백을 들었어요.

괜히 한 테이블당 하나씩 만들자고 한 것이 저라서, 더 비효율적이라면 바꿔야 한다고 생각합니다.

깊이 연관되어있는 테이블들 이를테면 room_status, rooms 와 user_status, users는 같은 마이그레이션 파일에서 만드는게 어떨까 합니닷

**Comment by hong-dev** [comment]
room_status와 rooms, user_status와 users를 한 파일로 합쳤습니다!

[before]
1. create_user_status
2. create_user
3. create_room_status
4. create_store
5. create_room

[after]
1. create_user
2. create_store
3. create_room
